## Exchange Categories

In [25]:
import pandas as pd
import re
import xlsxwriter

In [26]:
file_path = '/Users/carlottabonn/Documents/GitHub/GGTTIR/data/zwischenstaende/Neuste_Version2.xlsx'

In [35]:
df_regions = pd.read_excel(file_path,sheet_name='regions')
df_special = pd.read_excel(file_path,sheet_name='special_categories')
df_research = pd.read_excel(file_path,sheet_name='research_areas')

In [37]:
#df_regions

## Replace old categories by the new ones

## Regions

In [38]:
df_regions['Category']=df_regions['Category'].str.replace('Top 10 Think Tanks â€“ United States','Top Think Tanks in the United States')
df_regions['Category']=df_regions['Category'].str.replace('Top 100 Think Tanks â€“ Worldwide (Non-US)', 'Top Think Tanks worldwide (non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top 150 Think Tanks â€“ Worldwide (US and Non-US)', 'Top Think Tanks Worldwide (US and non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top 30 Think Tanks United States','Top Think Tanks in the United States')
df_regions['Category']=df_regions['Category'].str.replace('Top 25 Central and Eastern European Think Tanks', 'Top Think Tanks in Central and Eastern Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top 25 Think Tanks in Middle East and North Africa','Top Think Tanks in Middle East and North Africa(MENA)')
df_regions['Category']=df_regions['Category'].str.replace('Top 25 Think Tanks in Western Europe', 'Top Think Tanks in Western Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top 25 Think Tanks â€“ Worldwide (US and Non-US)','Top Think Tanks Worldwide (US and non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top 25 Think Tanks â€“ Worldwide (US and Non- US)','Top Think Tanks Worldwide (US and non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top 30 Central and Eastern European Think Tanks', 'Top Think Tanks in Central and Eastern Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top 30 Think Tanks in Mexico and Canada', 'Top Think Tanks in Mexico and Canada')
df_regions['Category']=df_regions['Category'].str.replace('Top 40 Think Tanks in Asia', 'Top Think Tanks in Asia')
df_regions['Category']=df_regions['Category'].str.replace('Top 25 Think Tanks in Asia', 'Top Think Tanks in Asia')
df_regions['Category']=df_regions['Category'].str.replace('Top 40 Think Tanks in Western Europe', 'Top Think Tanks in Western Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top 45 Think Tanks in China, India, Japan, and the Republic of Korea', 'Top Think Tanks in China, India, Japan, and the Republic of Korea')
df_regions['Category']=df_regions['Category'].str.replace('Top 45 Think Tanks in Middle East and North Africa (MENA)','Top Think Tanks in Middle East and North Africa(MENA)')
df_regions['Category']=df_regions['Category'].str.replace('Top 50 Think Tanks â€“ United States','Top Think Tanks in the United States')
df_regions['Category']=df_regions['Category'].str.replace('Top 50 Think Tanks â€“ Worldwide (Non-US)', 'Top Think Tanks worldwide (non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top 50 Think Tanks--United States','Top Think Tanks in the United States') 
df_regions['Category']=df_regions['Category'].str.replace('Top 55 Think Tanks in the United States','Top Think Tanks in the United States')
df_regions['Category']=df_regions['Category'].str.replace('Top 60 Think Tanks in Central and Eastern Europe', 'Top Think Tanks in Central and Eastern Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top 75 Think Tanks in Western Europe','Top Think Tanks in Western Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top Fifty Think Tanks in Western Europe','Top Think Tanks in Western Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top Fifty Think Tanks in the United States','Top Think Tanks in the United States')
df_regions['Category']=df_regions['Category'].str.replace('Top Fifty Think Tanks â€“ Worldwide (Non-US)','Top Think Tanks worldwide (non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top Think Tanks Worldwide (Non-US)','Top Think Tanks worldwide (non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top Think Tanks Worldwide (US and non- US)','Top Think Tanks Worldwide (US and non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top Think Tanks Worldwide (non-US)','Top Think Tanks worldwide (non-US)')
df_regions['Category']=df_regions['Category'].str.replace('Top Think Tanks in China, India, Japan,and the Republic of Korea', 'Top Think Tanks in China, India, Japan, and the Republic of Korea')
df_regions['Category']=df_regions['Category'].str.replace('Top Think Tanks in United States','Top Think Tanks in the United States')
df_regions['Category']=df_regions['Category'].str.replace('Top Think Tanks in the Middle East and North Africa (MENA)','Top Think Tanks in Middle East and North Africa(MENA)')
df_regions['Category']=df_regions['Category'].str.replace('Top Thirty Think Tanks in Asia','Top Think Tanks in Asia')
df_regions['Category']=df_regions['Category'].str.replace('Top Thirty Think Tanks in Central and Eastern Europe','Top Think Tanks in Central and Eastern Europe')
df_regions['Category']=df_regions['Category'].str.replace('Top Thirty Think Tanks in Sub-Saharan Africa','Top Think Tanks in Sub-Saharan Africa')
df_regions['Category']=df_regions['Category'].str.replace('Top Thirty Think Tanks in the Middle East and North Africa (MENA)','Top Think Tanks in Middle East and North Africa(MENA)')
df_regions['Category']=df_regions['Category'].str.replace('Top Thirty Think Tanks â€“ Worldwide (US and Non-US)', 'Top Think Tanks Worldwide (US and non-US)')

In [39]:
df_regions.tail()

,Rank,Think Tank,Category,Year,Country
8225,99,le centre d'études et de recherches aziz belal...,Top Think Tanks in Middle East and North Afric...,2018,Morocco
8226,100,kohelet policy forum (israel),Top Think Tanks in Middle East and North Afric...,2018,Israel
8227,101,arab center for scientific research and human ...,Top Think Tanks in Middle East and North Afric...,2018,Morocco
8228,102,institute of national planning (egypt),Top Think Tanks in Middle East and North Afric...,2018,Egypt
8229,103,confederation of moroccan enterprises (morocco),Top Think Tanks in Middle East and North Afric...,2018,Morocco

In [40]:
writer = pd.ExcelWriter('?.xlsx', engine='xlsxwriter')
df_regions.to_excel(writer,sheet_name='regions')
writer.save()

In [21]:
df_research['Category']=df_research['Category'].str.replace('Top 10 Domestic Economic Policy Think Tanks','Top Domestic Economic Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 Environment Think Tanks','Top Environment Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 Health Policy Think Tanks','Top Health Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 International Development','Top International Development Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 International Development Think Tanks','Top International Development Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 International Economic Policy Think Tanks','Top International Economics Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 Science and Technology Think Tanks','Top Science and Technology Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 Security and International Affairs Think Tanks','Top Security and International Affairs Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 10 Social Policy Think Tanks','Top Social Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 11 Environment Think Tanks','Top Environment Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 12 International Economic Policy Think Tanks','Top International Economics Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 15 Health Policy Think Tanks','Top Health Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 20 Energy and Resource Policy Think Tanks','Top Energy and Resource Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 20 Transparency and Good Governance Think Tanks','Top Transparency and Good Governance Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 25 Domestic Economic Policy Think Tanks','Top Domestic Economic Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 25 Environment Think Tanks','Top Environment Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 25 International Development Think Tank','Top International Development Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 25 International Economic Policy Think Tanks','Top International Economics Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 25 Science and Technology Think Tanks','Top Science and Technology Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 25 Security and International Affairs Think Tanks','Top Security and International Affairs Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 25 Social Policy Think Tanks','Top Social Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 30 Health Policy Think Tanks','Top Health Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 30 Transparency and Good Governance Think Tanks','Top Transparency and Good Governance Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 50 International Economic Policy Think Tanks','Top International Economics Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 50 Science and Technology Think Tanks','Top Science and Technology Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 50 Social Policy Think Tanks','Top Social Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 70 Environment Think Tanks','Top Environment Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 70 Security and International Affairs Think Tanks','Top Security and International Affairs Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 80 Domestic Economic Policy Think Tanks','Top Domestic Economic Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top 80 International Development Think Tanks','Top International Development Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Defense and National Security','Top Defense and National Security Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Environment Think Tanks','Top Environment Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Fifty Security and International Affairs Think Tanks','Top Security and International Affairs Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top International Development Think Tanks','Top International Development Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top International Economic Policy Think Tanks','Top International Economics Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top International Economics Think Tanks','Top International Economics Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Science and Technology Think Tanks','Top Science and Technology Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty Domestic Economic Policy Think Tanks','Top Domestic Economic Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty Environment Think Tanks','Top Environment Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty Health Policy Think Tanks','Top Health Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty International Development Think Tanks','Top International Development Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty International Economic Policy Think Tanks','Top International Economics Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty Science and Technology Think Tanks','Top Science and Technology Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty Social Policy Think Tanks','Top Social Policy Think Tanks')
df_research['Category']=df_research['Category'].str.replace('Top Thirty Transparency and Good Governance Think Tanks','Top Transparency and Good Governance Think Tanks')

In [22]:
df_research

,Rank,Think Tank,Category,Year,country
0,1,brookings institution usa,Top International Development Policy Think Tanks,2008,United States
1,2,overseas development institute (odi) uk,Top International Development Policy Think Tanks,2008,United Kingdom
2,3,council on foreign relations usa,Top International Development Policy Think Tanks,2008,United States
3,4,rand corporation us,Top International Development Policy Think Tanks,2008,United States
4,5,woodrow wilson international center for schola...,Top International Development Policy Think Tanks,2008,United States
5,6,institute of development studies uk,Top International Development Policy Think Tanks,2008,United Kingdom
6,7,center for global development usa,Top International Development Policy Think Tanks,2008,United States
7,8,international food policy research institute usa,Top International Development Policy Think Tanks,2008,United States
8,9,german development institute germany,Top International Development Policy Think Tanks,2008,Germany
9,10,international policy network uk,Top International Development Policy Think Tanks,2008,United Kingdom
10,10,atlas economic research foundation - usa,Top International Development Policy Think Tanks,2008,United States
11,10,international development research centre - ca...,Top International Development Policy Think Tanks,2008,Canada
12,1,brookings institution usa,Top Health Policy Think Tanks,2008,United States
13,2,national bureau of economic research usa,Top Health Policy Think Tanks,2008,United States
14,3,rand corporation usa,Top Health Policy Think Tanks,2008,United States
15,4,urban institute usa,Top Health Policy Think Tanks,2008,United States
16,5,american enterprise institute usa,Top Health Policy Think Tanks,2008,United States
17,6,council on foreign relations global health pro...,Top Health Policy Think Tanks,2008,United States
18,7,cato institute usa,Top Health Policy Think Tanks,2008,United States
19,8,fraser institute canada,Top Health Policy Think Tanks,2008,Canada
20,9,center for global development usa,Top Health Policy Think Tanks,2008,United States
21,10,civitas uk,Top Health Policy Think Tanks,2008,United Kingdom
22,10,national center for policy analysis usa,Top Health Policy Think Tanks,2008,United States
23,1,carnegie endowment for international peace usa,Top Environment Policy Think Tanks,2008,United States
24,2,brookings institution usa,Top Environment Policy Think Tanks,2008,United States
25,3,world resources institute usa,Top Environment Policy Think Tanks,2008,United States
26,4,worldwatch institute usa,Top Environment Policy Think Tanks,2008,United States
27,5,pew center on global climate change usa,Top Environment Policy Think Tanks,2008,United States
28,6,"belfer center for science and int'l affairs, k...",Top Environment Policy Think Tanks,2008,United States
29,7,resources for the future (rff) usa,Top Environment Policy Think Tanks,2008,United States
...,...,...,...,...,...
7349,0,"east africa living lakes network,uganda",List of Water Security Think Tanks (Alphabetic...,2018,Uganda
7350,0,"cabot institute, university of bristol, houses...",List of Water Security Think Tanks (Alphabetic...,2018,United States
7351,0,"cranfield water science institute,united kingdom",List of Water Security Think Tanks (Alphabetic...,2018,United Kingdom
7352,0,"environmental change institute, oxford,united ...",List of Water Security Think Tanks (Alphabetic...,2018,United Kingdom
7353,0,"institute of water (water aid),united kingdom",List of Water Security Think Tanks (Alphabetic...,2018,United Kingdom
7354,0,"overseas development institute (odi),united ki...",List of Water Security Think Tanks (Alphabetic...,2018,United Kingdom
7355,0,"water research centre,united kingdom",List of Water Security Think Tanks (Alphabetic...,2018,United Kingdom
7356,0,"center for global safe water, sanitation, and ...",List of Water Security Think Tanks (Alphabetic...,2018,United States
7357,0,"center for water-energy efficiency, uc davis,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7358,0,"circle of blue,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7359,0,"colorado state university water center, colora...",List of Water Security Think Tanks (Alphabetic...,2018,United States
7360,0,colorado water and energy research center (cwe...,List of Water Security Think Tanks (Alphabetic...,2018,United States
7361,0,"institute for environmental policy solutions, ...",List of Water Security Think Tanks (Alphabetic...,2018,United Kingdom
7362,0,"john hopkins water institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7363,0,"national water research institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7364,0,program in water conflict management and trans...,List of Water Security Think Tanks (Alphabetic...,2018,United States
7365,0,"pacific institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7366,0,"stroud water research center,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7367,0,"texas water resources institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7368,0,"the global water institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7369,0,"tufts institute of the environment,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7370,0,"water institute, university of florida at gain...",List of Water Security Think Tanks (Alphabetic...,2018,United States
7371,0,"water resources research center, umass-amherst...",List of Water Security Think Tanks (Alphabetic...,2018,United States
7372,0,"us corps of engineers,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7373,0,"water for food institute, university of nebras...",List of Water Security Think Tanks (Alphabetic...,2018,United States
7374,0,"water research center, dallas, pa,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7375,0,"water resources research center, university of...",List of Water Security Think Tanks (Alphabetic...,2018,United States
7376,0,"water resources research institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7377,0,"west virginia water research institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States
7378,0,"world resources institute,usa",List of Water Security Think Tanks (Alphabetic...,2018,United States

In [23]:
writer = pd.ExcelWriter('Neue_Kategorien.xlsx', engine='xlsxwriter')
df_research.to_excel(writer,sheet_name='research')
writer.save()

## Special Categories

In [24]:
df_special['Category']=df_special['Category'].str.replace(',Best Think Tanks with Political Party Affiliation','Best Think Tanks with a Political Party Affiliation')
df_special['Category']=df_special['Category'].str.replace('Best Advocay Campaign','Best Advocacy Campaign')
df_special['Category']=df_special['Category'].str.replace('Best External Relations/Public Engagement Program','Think Tanks with the Best External Relations/Public Engagement Program')
df_special['Category']=df_special['Category'].str.replace('Best For Profit Think Tanks','Best for Profit Think Tanks')
df_special['Category']=df_special['Category'].str.replace('Best Institutional Collaboration Involving Two or More Think','Best Institutional Collaboration Involving Two or More Think Tanks')
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace
df_special['Category']=df_special['Category'].str.replace